{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53335561-5cf7-4ba5-a5d0-9dc9e3b98503",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter\n",
    "from tkinter import ttk\n",
    "\n",
    "\n",
    "window=tkinter.Tk()\n",
    "window.title(\"Data Entry Form\")\n",
    "\n",
    "frame=tkinter.Frame(window)\n",
    "frame.pack()#pack by default is responsive and it will centre everything in the middle\n",
    "\n",
    "#saving user info\n",
    "user_info_frame=tkinter.LabelFrame(frame,text=\"user Informantion\")\n",
    "user_info_frame.grid(row=0,column=0,padx=20,pady=10)\n",
    "\n",
    "first_name_label=tkinter.Label(user_info_frame,text=\"first name\")\n",
    "first_name_label.grid(row=0,column=0)\n",
    "last_name_label=tkinter.Label(user_info_frame,text=\"first name\")\n",
    "last_name_label.grid(row=0,column=1)\n",
    "\n",
    "first_name_entry=tkinter.Entry(user_info_frame)\n",
    "last_name_entry=tkinter.Entry(user_info_frame)\n",
    "first_name_entry.grid(row=1,column=0)\n",
    "last_name_entry.grid(row=1,column=1)\n",
    "\n",
    "title_label=tkinter.Label(user_info_frame,text=\"title\")\n",
    "title_combobox=ttk.Combobox(user_info_frame,values=[\"\",\"Mr.\",\"Ms.\",\"Dr.\"])\n",
    "title_label.grid(row=0,column=2)\n",
    "title_combobox.grid(row=1,column=2)\n",
    "\n",
    "age_label=tkinter.Label(user_info_frame,text=\"Age\")\n",
    "age_spinbox=tkinter.Spinbox(user_info_frame,from_=18,to=110)\n",
    "age_label.grid(row=2,column=0)\n",
    "age_spinbox.grid(row=3,column=0)\n",
    "\n",
    "nationality_label=tkinter.Label(user_info_frame,text=\"Ntionality\")\n",
    "nationality_combobox=ttk.Combobox(user_info_frame,values=[\"India\"])\n",
    "nationality_label.grid(row=2,column=1)\n",
    "nationality_combobox.grid(row=3,column=1)\n",
    "\n",
    "for widget in user_info_frame.winfo_children():\n",
    "    widget.grid_configure(padx=10,pady=5)\n",
    "\n",
    "#saving course info\n",
    "courses_frame=tkinter.LabelFrame(frame)\n",
    "courses_frame.grid(row=1,column=0,sticky=\"news\",padx=20,pady=10)\n",
    "\n",
    "registered_label=tkinter.Label(courses_frame,text=\"Registration Status\")\n",
    "regisrered_check=tkinter.Checkbutton(courses_frame,text=\"Currently Registered\")\n",
    "registered_label.grid(row=0,column=0)\n",
    "regisrered_check.grid(row=1,column=0)\n",
    "\n",
    "numcourses_label=tkinter.Label(courses_frame,text=\"# compeletes courses\")\n",
    "numcourses_spinbox=tkinter.Spinbox(courses_frame,from_=0,to=\"infinity\")                                   \n",
    "numcourses_label.grid(row=0,column=1)\n",
    "numcourses_spinbox.grid(row=1,column=1) \n",
    "\n",
    "numsemesters_label=tkinter.Label(courses_frame,text=\"# Semesters\")\n",
    "numsemseters_spinbox=tkinter.Spinbox(courses_frame,from_=0,to=\"infinity\")\n",
    "numsemesters_label.grid(row=0,column=2)\n",
    "numsemseters_spinbox.grid(row=1,column=2)\n",
    "\n",
    "for widget in courses_frame.winfo_children():\n",
    "    widget.grid_configure(padx=10,pady=5)\n",
    "\n",
    "#Accept terms\n",
    "terms_frame=tkinter.LabelFrame(frame,text=\"terms & conditions\")\n",
    "terms_frame.grid(row=2,column=0,sticky=\"news\",padx=20,pady=10)\n",
    "terms_check=tkinter.Checkbutton(terms_frame,text=\"I accept the terms and conditions\")\n",
    "terms_check.grid(row=0,column=0)\n",
    "\n",
    "#Button\n",
    "button=tkinter.Button(frame,text=\"Enter data\")\n",
    "button.grid(row=3,column=0,sticky=\"news\",padx=20,pady=10)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "window.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
